BEGIN {
  # phase and data are sent by awk (see phreeqc2bil.sh)
  # phase = 0; # -> Log10EquilibriumConstantOfHomogeneousReactionInWater.h
  # phase = 1; # -> Log10DissociationConstantOfCementHydrationProduct.h
  ndata = split(data,dat,"-");
  title = "";
  if(ndata > 0) {
    print "/* This file was generated by awk using the program phreeqc2bil.awk"
    print " * and the script phreeqc2bil.sh (see \"scripts\" folder) */"
    if(phase == 0) {
      title = "LOG10EQUILIBRIUMCONSTANTOFHOMOGENEOUSREACTIONINWATER_";
      expr1 = "SOLUTION_SPECIES"
      expr2 = "PHASES"
    } else if(phase == 1) {
      title = "LOG10DISSOCIATIONCONSTANTOFCEMENTHYDRATIONPRODUCT_";
      expr1 = "PHASES"
      expr2 = "!PHASES"
    } else {
      title = "";
      expr1 = "SOLUTION_SPECIES"
      expr2 = "!PHASES"
    }
    print "#ifndef "title dat[1] "_H_IN";
    print "#define "title dat[1] "_H_IN";
    print;
    print "#include \"TemperatureDependenceOfLog10EquilibriumConstant.h\""
    print;
  } else {
    print "no data!";
    exit;
  }
  phasename = "";
}

END {
  print "#endif"
}

$1 ~ expr1 , $1 ~ expr2 {

  if(phase > 0 && (NF == 1 && $1 != "PHASES")) {phasename = $1;}

  # The sign "=" pretends it is a reaction
  if($0 ~ /=/ ) {
    # Remove the blank at the beginning of the line
    gsub(/^([ \t])*/,"",$0);

    # Print the reaction with possibly the phase name
    printf("\n/* ");
    if(phase > 0) {printf("Phase = %s ; ",phasename);}
    printf("Reaction: %s",$0);
    printf(" */\n");

    #if(phase > 0) {$1 = gensub(/(\()([a-zA-Z1-9]*)(\))([^1-9]|$)/,"\\2\\4","g",phasename);}
    if(phase > 0) {$1 = transform(phasename);}
    gsub(/([ \t])+(=)([ \t])+/,"__",$0);
    gsub(/([ \t])+(+)([ \t])+/,"_",$0);
    gsub(/[+-][1-9]?/,"",$0);

    r = transform($0);
  }

  if($0 ~ /-analytical_expression/) {
    sub(/^[ \t]*-analytical_expression[ \t]*/,"TemperatureDependenceOfLog10EquilibriumConstant(T,");
    sub(/$/,")");
    gsub(/ /,",");
    if(phase == 0) {
      print "#define Log10EquilibriumConstantOfHomogeneousReactionInWater_"r"(T)\\";
      print "        "$0;
    } else if(phase == 1) {
      print "#define Log10DissociationConstantOfCementHydrationProduct_"r"(T)\\";
      print "        "$0;
    }
  }
}

function transform(t) {
  # Transform "(X)n" in "XX..X" (n times) and "I.J" in "IdJ"
  
  r = t;
  # "(X) " -> "X "
  if(match(t,/(\()([a-zA-Z1-9]*)(\))([^1-9]|$)/) > 0) {
    r = gensub(/(\()([a-zA-Z1-9]*)(\))([^1-9]|$)/,"\\2\\4","g",r);
  # "(X)1" -> "X"
  } else if(match(t,/(\()([a-zA-Z1-9]*)(\))(1([^.]))/) > 0) {
    r = gensub(/(\()([a-zA-Z1-9]*)(\))(1)/,"\\2","g",r);
  # "(X)2" -> "XX"
  } else if(match(t,/(\()([a-zA-Z1-9]*)(\))(2([^.]))/) > 0) {
    r = gensub(/(\()([a-zA-Z1-9]*)(\))(2)/,"\\2\\2","g",r);
  # "(X)3" -> "XXX"
  } else if(match(t,/(\()([a-zA-Z1-9]*)(\))(3([^.]))/) > 0) {
    r = gensub(/(\()([a-zA-Z1-9]*)(\))(3)/,"\\2\\2\\2","g",r);
  # "(X)4" -> "XXXX"
  } else if(match(t,/(\()([a-zA-Z1-9]*)(\))(4([^.]))/) > 0) {
    r = gensub(/(\()([a-zA-Z1-9]*)(\))(4)/,"\\2\\2\\2\\2","g",r);
  # "(X)5" -> "XXXXX"
  } else if(match(t,/(\()([a-zA-Z1-9]*)(\))(5([^.]))/) > 0) {
    r = gensub(/(\()([a-zA-Z1-9]*)(\))(5)/,"\\2\\2\\2\\2\\2","g",r);
  # "(X)6" -> "XXXXXX"
  } else if(match(t,/(\()([a-zA-Z1-9]*)(\))(6([^.]))/) > 0) {
    r = gensub(/(\()([a-zA-Z1-9]*)(\))(6)/,"\\2\\2\\2\\2\\2\\2","g",r);
  # "(X)7" -> "XXXXXXX"
  } else if(match(t,/(\()([a-zA-Z1-9]*)(\))(7([^.]))/) > 0) {
    r = gensub(/(\()([a-zA-Z1-9]*)(\))(7)/,"\\2\\2\\2\\2\\2\\2\\2","g",r);
  # "(X)8" -> "XXXXXXXX"
  } else if(match(t,/(\()([a-zA-Z1-9]*)(\))(8([^.]))/) > 0) {
    r = gensub(/(\()([a-zA-Z1-9]*)(\))(8)/,"\\2\\2\\2\\2\\2\\2\\2\\2","g",r);
  # "(X)9" -> "XXXXXXXXX"
  } else if(match(t,/(\()([a-zA-Z1-9]*)(\))(9([^.]))/) > 0) {
    r = gensub(/(\()([a-zA-Z1-9]*)(\))(9)/,"\\2\\2\\2\\2\\2\\2\\2\\2\\2","g",r);
  } else {}

  # "I.J" -> "IdJ"
  r = gensub(/([0-9])(\.)([0-9])/,"\\1d\\3","g",r); # Replace a "." by "d"
  return(r);
}
